apiVersion: apps/v1 
kind: Deployment
metadata:
  name: prom
  labels:
    app: prom
spec:
  selector:
    matchLabels:
      app: prom
      env: prod
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: prom
        env: prod
    spec: 
      containers:
      - image: vimal13/prometheus
        name: prom
        ports:
        - containerPort: 9090
          name: prom
        volumeMounts:
        - name: prometheus-persistent-storage
          mountPath: /prometheus
      volumes:
      - name: prometheus-persistent-storage
        persistentVolumeClaim:
          claimName: prom-pv-claim
